GO
IF DB_ID('$(DbName)') IS NOT NULL 
BEGIN
  ALTER DATABASE $(DbName) SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
  DROP DATABASE $(DbName);
END
GO
EXECUTE AS LOGIN = 'SA';
GO
CREATE DATABASE $(DbName) WITH TRUSTWORTHY ON;
GO
