IF OBJECT_ID('tSQLt.SQLServerVersion') IS NOT NULL DROP FUNCTION tSQLt.SQLServerVersion;
GO
---Build+
GO
CREATE FUNCTION tSQLt.SQLServerVersion()
RETURNS TABLE
AS
RETURN
SELECT NULL Major;
GO
---Build-
GO
SELECT 
SERVERPROPERTY('ProductVersion'),
PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(MAX)),4),
PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(MAX)),3),
PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(MAX)),2),
PARSENAME(CAST(SERVERPROPERTY('ProductVersion') AS NVARCHAR(MAX)),1)
