IF OBJECT_ID('tSQLt.Private_CleanUp') IS NOT NULL DROP PROCEDURE tSQLt.Private_CleanUp;
GO
---Build+
GO
CREATE PROCEDURE tSQLt.Private_CleanUp
  @FullTestName NVARCHAR(MAX),
  @ErrorMsg NVARCHAR(MAX) OUTPUT
AS
BEGIN
  RETURN;
END;
GO
---Build-
GO
